### ISSUE TITLE
Re alignment of Donation Content

### ISSUE THREAD

**Issue by Easybuoy** [Say-Their-Name/say-their-names-web#74]
FILL OUT THE FORM BELOW OR THE ISSUE WILL BE AUTO-CLOSED

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion

**Description (Please type a clear and concise description below)** 
On the donations page, if a donation is not found, the content is not properly ordered.

To replicate load `/donations/aaa` route on your machine

See screenshot below, the `No Donations Found` should not be at the top

<img width="797" alt="Screenshot 2020-06-08 at 07 17 30" src="https://user-images.githubusercontent.com/24660100/83999139-0983ba00-a95a-11ea-8aaf-72938ffa96cb.png">

After this is done, head over  to the `routes/index.js` file, and change the route from
`<Route path="/donations/:identifier?" component={Donations} exact />`
to 
`<Route path="/donations" component={Donations} exact />`

We are changing the route because we don't need to load a donation by identifier anymore.

**Comment by kiahjade** [comment]
Going to take a look at this. No idea if I'll be able to solve so happy for other people to jump in.

**Comment by Easybuoy** [comment]
If you have any questions you can reach out, happy to help

**Comment by kiahjade** [comment]
Thanks, currently I'm having trouble running the app due to eslint... I've installed and ran as directed on the readme but getting compilation error due to eslint. 
Do you know if anyone else has anything similar? 
<img width="1139" alt="Screenshot 2020-06-08 at 11 03 57" src="https://user-images.githubusercontent.com/45144659/84018824-61311e00-a978-11ea-81ed-fb7eea236dfc.png">

**Comment by Easybuoy** [comment]
Can you run the command `yarn lint:fix` on your terminal

**Comment by Easybuoy** [comment]
Fixed in #79
